# Generated by Django 4.1.7 on 2023-03-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_mainimage_smallimages_delete_box_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainimage',
            name='small_images',
        ),
        migrations.AddField(
            model_name='mainimage',
            name='small_images',
            field=models.ManyToManyField(to='myapp.smallimages'),
        ),
    ]
