# Generated by Django 4.1.7 on 2023-03-17 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_mainimage_small_images_mainimage_small_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallimages',
            name='label',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
