# Generated by Django 4.1.7 on 2023-03-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_mainimage_small_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainimage',
            name='small_images',
            field=models.ManyToManyField(to='myapp.smallimages'),
        ),
    ]
