# Generated by Django 4.1.7 on 2023-04-20 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_mainimage_small_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainimage',
            name='price',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
