# Generated by Django 4.1.7 on 2023-04-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='mainimage',
            name='colors',
            field=models.ManyToManyField(to='myapp.shoecolor'),
        ),
        migrations.AddField(
            model_name='mainimage',
            name='sizes',
            field=models.ManyToManyField(to='myapp.shoesize'),
        ),
    ]
